### PR TITLE
Blog home page

### LINKED ISSUE #2669: [Feature Request]: Design a blog home page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to design a blog home page 

### Use Case

Here cards will be used to display title and little info about the blog,from wherein the user can click on the cards to read whichever blog they feel like reading.Data will be mapped into it.

### Benefits

Enhanced feature,ui and readability

### Add ScreenShots

image
kind of like this with cards and data mapping

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by komal-agarwal5**
## Related Issue

Fix #2669 

## Description
I have made a blogs home page to redirect to various blogs
- Blog card component made
- Component compatible for both light and dark mode
- Blog data JSON made
- Mapped in blog page
- Display all in grid container in main blog page
- Added blogs with image,title,description and link to it

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

https://github.com/user-attachments/assets/69e173c8-ade9-4d46-bfcd-cf3f91527fe5

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have followed the code style guidelines of this project.
- [x] I have checked for any existing open issues that my pull request may address.
- [x] I have ensured that my changes do not break any existing functionality.
- [x] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [x] I have read the resources for guidance listed below.
- [x] I have followed security best practices in my code changes.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Please read the following resources before submitting your contribution:

- [ ] [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [ ] [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [ ] [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [ ] [Markdown Guide](https://www.markdownguide.org/)
- [ ] [MDX Documentation](https://mdxjs.com/docs/)
- [ ] [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- [ ] [Tabs: Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [ ] [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [ ] [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex) 

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **level1** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **level2**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Level1:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Level2:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Level3:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

### CODE REVIEW

**Comment by Ajay-Dhangar** [comment]
@komal-agarwal5, I have created the blog's page based on our requirements. You can check it out at https://codeharborhub.github.io/blogs/.

**Comment by Ajay-Dhangar** [comment]
You can update its content or try to address other issues.

**Comment by komal-agarwal5** [comment]
> You can update its content or try to address other issues.

@Ajay-Dhangar I have mapped content for existing 9 blogs
and there is slight difference in the UI bw the 2 , I have image hover effect also in the cards I made 
If I add more blogs can this be merged then?
Or you can say if any more changes u want in the cards I can do that then?

**Comment by Ajay-Dhangar** [comment]
> > You can update its content or try to address other issues.
> 
> @Ajay-Dhangar I have mapped content for existing 9 blogs and there is slight difference in the UI bw the 2 , I have image hover effect also in the cards I made If I add more blogs can this be merged then? Or you can say if any more changes u want in the cards I can do that then?

@komal-agarwal5, thanks for putting in the work on this blog home page feature. Your initial approach was a great starting point, but there were some issues with how you implemented the blog card component. I've made some changes to the codebase and added an example blog card for you to reference. You can delete your added code, pull our main branch, and then add images and content to the empty blog cards. I'll assign this issue the same level as before, and once you've made these updates we can merge the PR.

**Comment by komal-agarwal5** [comment]
> > > You can update its content or try to address other issues.
> > 
> > 
> > @Ajay-Dhangar I have mapped content for existing 9 blogs and there is slight difference in the UI bw the 2 , I have image hover effect also in the cards I made If I add more blogs can this be merged then? Or you can say if any more changes u want in the cards I can do that then?
> 
> @komal-agarwal5, thanks for putting in the work on this blog home page feature. Your initial approach was a great starting point, but there were some issues with how you implemented the blog card component. I've made some changes to the codebase and added an example blog card for you to reference. You can delete your added code, pull our main branch, and then add images and content to the empty blog cards. I'll assign this issue the same level as before, and once you've made these updates we can merge the PR.

Ok thank you so much, I will do it as said.

**Comment by komal-agarwal5** [comment]
https://github.com/user-attachments/assets/6585ad2c-6509-496e-a79e-3ea5917d8389

@Ajay-Dhangar done

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Pull request merged**
