### PR TITLE
Blogs shifted and redesigned

### PR DESCRIPTION
**Pull request by komal-agarwal5**
## Description

I have shifted the blogs directory and redesigned it by adding a home page having blog cards with description of blogs,image and title, aligned in grid layout.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

https://github.com/CodeHarborHub/codeharborhub.github.io/assets/122633300/fae44c71-ad9b-47bc-900b-e4ba8768d38d

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have followed the code style guidelines of this project.
- [x] I have checked for any existing open issues that my pull request may address.
- [x] I have ensured that my changes do not break any existing functionality.
- [x] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [x] I have read the resources for guidance listed below.
- [x] I have followed security best practices in my code changes.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Please read the following resources before submitting your contribution:

- [ ] [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [ ] [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [ ] [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [ ] [Markdown Guide](https://www.markdownguide.org/)
- [ ] [MDX Documentation](https://mdxjs.com/docs/)
- [ ] [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- [ ] [Tabs: Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [ ] [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [ ] [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex) 

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **level1** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **level2**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Level1:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Level2:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Level3:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

### CODE REVIEW

**Comment by komal-agarwal5** [comment]
@Ajay-Dhangar I needed a help
My PR NO 329 was merged many days ago till day before yesterday it was visible in leaderboard but since yesterday its not visible could u pls help me out with this?

**Comment by komal-agarwal5** [comment]
@Ajay-Dhangar Sir but I didn't do documentation work here,I have designed the main blogs page then I guess documentation level isn't needed?

And sir My PR NO 329 was merged many days ago till day before yesterday it was visible in leaderboard but since yesterday its not visible could u pls help me out with this?

**Review by Ajay-Dhangar — CHANGES_REQUESTED** [review]
@komal-agarwal5, this approach isn't correct. Our blog directory is already set up with plugins, so you only need to create one file: pages/blogs/index.tsx. In this file, write the code for the blog cards, including the image, blog title, description, and link to our blogs. Please do not change the entire blog directory structure.

**Comment by Ajay-Dhangar** [comment]
> @Ajay-Dhangar I needed a help My PR NO 329 was merged many days ago till day before yesterday it was visible in leaderboard but since yesterday its not visible could u pls help me out with this?

@komal-agarwal5, I think your PRs score is currently at up to 120, but it might be removed by the program manager.

**Comment by Ajay-Dhangar** [comment]
@sanjay-kv, can you help @komal-agarwal5 with solving their doubts?

**Comment by sanjay-kv** [comment]
https://github.com/GSSoC24/Contributor/discussions/categories/q-a

can u raise the issue with respective PR link here. i will get you solution eod

**Comment by komal-agarwal5** [comment]
> https://github.com/GSSoC24/Contributor/discussions/categories/q-a
> 
> can u raise the issue with respective PR link here. i will get you solution eod

Yes sir I have raised it

**Comment by komal-agarwal5** [comment]
> @komal-agarwal5, this approach isn't correct. Our blog directory is already set up with plugins, so you only need to create one file: pages/blogs/index.tsx. In this file, write the code for the blog cards, including the image, blog title, description, and link to our blogs. Please do not change the entire blog directory structure.

Ok I am making the corrections

**Comment by komal-agarwal5** [comment]
@Ajay-Dhangar please check now if it is ok

**Review by Ajay-Dhangar — CHANGES_REQUESTED** [review]
@komal-agarwal5, please close this pull request. First, pull from our main branch and then rewrite the code. Please do not modify the `blog` directory as it contains plugins and is connected to our structure, making it not a good practice to alter it.

### Instructions:

1. **Directory Structure**:
   - Create a new folder at `src/pages/blogs/`.
   - Create a new file `index.tsx` inside the `src/pages/blogs/` folder.
   - Create another folder for the blog data at `src/data/blogs/`.
   - Add a new file `index.tsx` inside the `src/data/blogs/` folder with the blog data.

2. **Blog Data**:
   - The blog data should be in JSON format, structured as an array of objects.
   - Example of `src/data/blogs/index.tsx`:

     ```tsx
     const blogs = [
       {
         id: 1,
         title: "First Blog Post",
         content: "This is the content of the first blog post.",
         author: "Author One",
         date: "2024-07-01",
         imageUrl: "https://example.com/image1.jpg",
         link: "https://example.com/blog1"
       },
       {
         id: 2,
         title: "Second Blog Post",
         content: "This is the content of the second blog post.",
         author: "Author Two",
         date: "2024-07-02",
         imageUrl: "https://example.com/image2.jpg",
         link: "https://example.com/blog2"
       }
     ];

     export default blogs;
     ```

3. **Import Blog Data**:
   - Import the blog data into `src/pages/blogs/index.tsx`.
   - Example of `src/pages/blogs/index.tsx`:

     ```tsx
     import React from 'react';
     import blogs from '../../data/blogs';

     const BlogsPage = () => {
       return (
         <div>
           <h1>Blogs</h1>
           <ul>
             {blogs.map(blog => (
               <li key={blog.id}>
                 <h2>{blog.title}</h2>
                 <img src={blog.imageUrl} alt={blog.title} style={{ width: '200px', height: 'auto' }} />
                 <p>{blog.content}</p>
                 <p>By: {blog.author} on {blog.date}</p>
                 <a href={blog.link} target="_blank" rel="noopener noreferrer">Read more</a>
               </li>
             ))}
           </ul>
         </div>
       );
     };

     export default BlogsPage;
     ```

By following these steps, we ensure that the `blog` directory remains unaltered and properly structured. This approach allows us to maintain a clean and organized codebase.

**Comment by komal-agarwal5** [comment]
@Ajay-Dhangar ok changing it
Actually when I was doing it without modifying the name of original blog directory then I was facing routing issue as on clicking the "blog" option from navbar it is redirecting to current blog page and not the blog page of index.tsx as both directories have same name "blog". How do i solve this could u pls tell?

**Comment by Ajay-Dhangar** [comment]
@komal-agarwal5, Don't worry, our structure for blog content is organized as `blog/...`, while `/blogs` specifically serves as the page for all blog cards.

**Comment by komal-agarwal5** [comment]
> @komal-agarwal5, Don't worry, our structure for blog content is organized as `/blog/...`, while `/blogs` specifically serves as the page for all blog cards.

Ok got it

**Pull request closed without merging**
