### PR TITLE
Climbing stair solution added

### PR DESCRIPTION
**Pull request by Vipullakum007**
## Related Issue

Fixed : #418 

## Description

i have added solution of "Climbing Stairs" Solution

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

Screenshot (611)
Screenshot (612)
Screenshot (613)
Screenshot (614)
Screenshot (615)
Screenshot (616)
Screenshot (617)
Screenshot (618)
Screenshot (619)
Screenshot (620)

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

### CODE REVIEW

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar , i have added solution to paths to reach origin .
can please make it level 3
Reason:

make same as "Two sum Problem" as @Ajay-Dhangar (you ) suggested
added 4 Approach

**Comment by rajnishdesai23** [comment]
@Vipullakum007  don't spam issues please

**Comment by Vipullakum007** [comment]
@rajnishdesai23 , sorry bhai i have don't have idea before , i have knowledge about that tomorrow . please don't ban me

**Comment by Vipullakum007** [comment]
hey @rajnishdesai23 , don't make my PR close i don't make spam in FUTURE

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar , i have added solution to paths to reach origin .
can please make it level 3
Reason:

1. make same as "Two sum Problem" as @Ajay-Dhangar (you ) suggested
2. added 4 Approach

**Comment by Ajay-Dhangar** [comment]
> hey @Ajay-Dhangar , i have added solution to paths to reach origin . can please make it level 3 Reason:
> 
> 1. make same as "Two sum Problem" as @Ajay-Dhangar (you ) suggested
> 2. added 4 Approach

@Vipullakum007 I know your content is good, but it needs more improvement and better explanation. Based on the current level, I can't assign a level 3 rating. Level 3 is for very advanced work, like that of a professional. This documentation page should not be rated at level 3 as the code is more suited to level 2. The basics are aligned with level 1. I have already completed the setup and provided resources on how to write, so you only need to write the content. This is similar to a simple markdown file implementation. Based on GSSOC'24 guidelines, I can't assign a level 3 rating.

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Comment by Vipullakum007** [comment]
> hey @Ajay-Dhangar , how to make solution for level 3 label. can you point out features how to make professional repo ?

hey @Ajay-Dhangar ,please answer so i follow that points in future

**Pull request merged**
