### PR TITLE
Docs: Added Solutions to Leetcode 445

### LINKED ISSUE #1116: [Feature Request]: Leetcode Problem 445 - (Add Two Numbers II - Medium)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Provide Solution To Leetcode Problem 445 - (Add Two Numbers II)

### Use Case

I would add proper solutions for the problem in three different programing languages i.e C++,Java,and Python with proper documentation

### Benefits

Users can access solution to problem 445

### Add ScreenShots

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by shreyash3087**
## Related Issue

Closes #1116

## Description

This PR adds the solution to leetcode problem 445 - (Add Two Numbers II)

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

screencapture-localhost-3000-dsa-solutions-lc-solutions-0400-0499-add-two-numbers-ii-2024-06-13-17_54_39

## Checklist
- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have followed the code style guidelines of this project.
- [X] I have checked for any existing open issues that my pull request may address.
- [X] I have ensured that my changes do not break any existing functionality.
- [X] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [X] I have read the resources for guidance listed below.
- [X] I have followed security best practices in my code changes.

## Additional Context

N/A

### CODE REVIEW

**Comment by shreyash3087** [comment]
@Ajay-Dhangar Why is it showing Duplicate Lines on QualityGate. I have not changed anything other than what im required to,you can check it in the Files Changed Section.
Kindly Help Its showing that in both of my PRs

Thankyou

**Comment by shreyash3087** [comment]
PS- I made a new clone of the repo to work on the latest repo,the pr was working fine on the older clones,but this times its showing this

**Comment by shreyash3087** [comment]
@Ajay-Dhangar Kindly Review and Merge

Thankyou

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Pull request merged**
