### PR TITLE
Added String topic in DSA

### PR DESCRIPTION
**Pull request by SadafKausar2025**
## Related Issue #920
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description

[Please include a brief description of the changes or features added]

## Type of PR

- [x] Documentation update

## Screenshots / Videos (if applicable)
Screenshot (1972)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hello @Ajay-Dhangar 
please review this PR

**Comment by SadafKausar2025** [comment]
https://github.com/CodeHarborHub/codeharborhub.github.io/assets/137484958/123a3f8f-e828-476a-ae3f-fe9874c20898

**Comment by SadafKausar2025** [comment]
hello @Ajay-Dhangar 
Is this documentation all right?

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Pull request merged**
