### PR TITLE
Added Solutions for Leetcode 2353

### PR DESCRIPTION
**Pull request by shreyash3087**
## Related Issue

None

## Description

This PR Provides Solutions for Leetcode 2353 and is made in context to - https://github.com/GSSoC24/Contributor/discussions/502#discussioncomment-10100409.

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

screencapture-localhost-3000-dsa-solutions-lc-solutions-2300-2399-design-a-food-rating-system-2024-07-20-14_08_18

## Checklist
- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have followed the code style guidelines of this project.
- [X] I have checked for any existing open issues that my pull request may address.
- [X] I have ensured that my changes do not break any existing functionality.
- [X] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [X] I have read the resources for guidance listed below.
- [X] I have followed security best practices in my code changes.

## Additional Context

This PR is made in context to sanjay sir's advice in - https://github.com/GSSoC24/Contributor/discussions/502#discussioncomment-10100409

In order to compensate for the PR losses due to the url issue.

### CODE REVIEW

**Comment by shreyash3087** [comment]
@Ajay-Dhangar I hope you are doing well.

I have made this PR in accordance of Sanjay Sir's Advice in - https://github.com/GSSoC24/Contributor/discussions/502#discussioncomment-10100409

So Far 8 of my PR has been deleted from the leaderboard due to the glitch

these are the prs-

https://github.com/CodeHarborHub/codeharborhub.github.io/pull/995

https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1015

https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1022

https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1080

https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1112

https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1115

https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1146

https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1151

that are deleted from lb 

To compoensate for these PR I will raise 2,3 PR's as sanjay sir said in the discussion and i request you to merge them with level 3 each so that it compensates for the lost PR's

Merging this PR as level 3 will give me points equivalent to 4 of my lost PR's

Therfore i request you to consider this message before merging this pr

**Comment by Ajay-Dhangar** [comment]
Hey @shreyash3087, could you please reopen your PRs? They aren't currently being counted towards your score on the leaderboard. Feel free to make changes to grammar and maybe add a few words. After you're done, I'll merge them again with the main branch, and they will be counted towards your score.

**Comment by Ajay-Dhangar** [comment]
> Hey @shreyash3087, could you please reopen your PRs? They aren't currently being counted towards your score on the leaderboard. Feel free to make changes to grammar and maybe add a few words. After you're done, I'll merge them again with the main branch, and they will be counted towards your score.

@shreyash3087, you need to add something to this file to count its score on your leaderboard. Then, you can try it at the bottom. 

```md
---

<h2>Authors:</h2>

<div style={{display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: '10px'}}>
{['github_username'].map(username => (
 <Author key={username} username={username} />
))}
</div>
```

for your author profile in docs

**Comment by shreyash3087** [comment]
@Ajay-Dhangar But those PR's are already merged so how can i reopen them?

That's why i made this PR so that you can merge this with Level 3 and this will compenasate for 3 of my PR's that aren't being counted - 

For Example these are the PR that are not being counted - 

https://github.com/CodeHarborHub/codeharborhub.github.io/pull/995 - Level 2 PR - Score 25
https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1015 - Level 1 PR - Score 10
https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1022 - Level 1 PR - Score 10

Total Score - 45 = Level 3

So you can merge this pr with level 3 and it will compensate for those PR Points

**Comment by Ajay-Dhangar** [comment]
> @Ajay-Dhangar I hope you are doing well.
> 
> I have made this PR in accordance of Sanjay Sir's Advice in - [GSSoC24/Contributor#502 (reply in thread)](https://github.com/GSSoC24/Contributor/discussions/502#discussioncomment-10100409)
> 
> So Far 8 of my PR has been deleted from the leaderboard due to the glitch
> 
> these are the prs-
> 
> #995
> 
> #1015
> 
> #1022
> 
> #1080
> 
> #1112
> 
> #1115
> 
> #1146
> 
> #1151
> 
> that are deleted from lb
> 
> To compoensate for these PR I will raise 2 PR's as sanjay sir said in the discussion and i request you to merge them with level 3 each so that it compensates for the lost PR's
> 
> Merging this PR as level 3 will give me points equivalent to 4 of my lost PR's
> 
> Therfore i request you to consider this message before merging this pr



Hey @shreyash3087, to calculate the score for your leaderboard, you'll need to add something to those files and then try it out at the bottom. Below is the code you need to include for your author profile in the documentation:

```md
---

<h2>Authors:</h2>

<div style={{display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: '10px'}}>
{['github_username'].map(username => (
 <Author key={username} username={username} />
))}
</div>
```

**Comment by shreyash3087** [comment]
@Ajay-Dhangar I Added  - 

---

<h2>Authors:</h2>

<div style={{display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: '10px'}}>
{['github_username'].map(username => (
 <Author key={username} username={username} />
))}
</div>

To all of my previous 51 PR's

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Pull request merged**
