### PR TITLE
Added Solution for a problem 244

### LINKED ISSUE #3530: [Feature Request]: want to add Add Solution for a problem 244 (Premium)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

0244- Shortest Word Distance II

The problem provides us with the task of designing a data structure that must be able to compute the shortest distance between any two distinct strings within an array of strings. This implies that we first need to initialize the data structure with an array of strings, which we'll refer to as wordsDict. Once initialized, we should be able to query this data structure with two different strings, and it should return the smallest possible index difference between these two strings within the wordsDict array.

This could be visualized as an array where we want to find the minimum distance between two elements, where the elements are the positions of the words we're interested in. For example, if wordsDict is ["practice", "makes", "perfect", "coding", "makes"], and we query for the distance between "coding" and "practice", the returned value should be 3, as the closest "practice" to "coding" is three indices away.

### Use Case

Let's demonstrate how the WordDistance class and its methods work using a simple example.

Suppose our wordsDict is ["the", "quick", "brown", "fox", "quick"]. We initialize the WordDistance class with this list of strings. During the initialization process, the class builds the hash map self.d which will contain:

"the" -> [0]
"quick" -> [1, 4]
"brown" -> [2]
"fox" -> [3]
Now, let's say we want to find the shortest distance between the words "brown" and "quick". We call the shortest method with these two words. Here's what happens inside this method:

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by pallasivasai**
## Related Issue

Fix #3530 

## Type of PR

- [x] Feature enhancement
- [x] Documentation update

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have followed the code style guidelines of this project.
- [x] I have checked for any existing open issues that my pull request may address.
- [x] I have ensured that my changes do not break any existing functionality.
- [x] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [x] I have read the resources for guidance listed below.
- [x] I have followed security best practices in my code changes.

### CODE REVIEW

**Review by Ajay-Dhangar — CHANGES_REQUESTED** [review]
Please delete the `0185-Department-Top-Three-Salaries.md` file because it is a duplicate. This file is already available in this repository.

**Comment by pallasivasai** [comment]
Okay Done please check now @Ajay-Dhangar

**Review by Ajay-Dhangar — CHANGES_REQUESTED** [review]
This code doesn't complete the problem.

**Comment by pallasivasai** [comment]
can you explain it more detail but this code is enough!

**Comment by Ajay-Dhangar** [comment]
> can you explain it more detail but this code is enough!

@pallasivasai, please complete your code as it is currently unfinished. Thank you!

**Review by Ajay-Dhangar — CHANGES_REQUESTED** [review]
@pallasivasai, we need more content after line no. 244 because your code is incomplete. The function "shortest" is not defined, so the code will not run. Please provide the missing code or a link to the completed gist.

**Comment by sivaprasath2004** [comment]
Hello @Ajay-Dhangar can i solve this PR..

**Comment by Ajay-Dhangar** [comment]
> Hello @Ajay-Dhangar can i solve this PR..

@sivaprasath2004, Okay

**Pull request closed without merging**
