### PR TITLE
Added Recursion topic in DSA

### LINKED ISSUE #994: [Documentation Update]: Adding Recursion Topic in DSA
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

.

### Suggested Change

.

### Rationale

After linkedlist I want to add Recursion topic of DSA

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by SadafKausar2025**
## Related Issue 

Fix #994

[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

## Description

[Please include a brief description of the changes or features added]

## Type of PR

- [x] Documentation update

## Screenshots / Videos (if applicable)
Screenshot (1974)

Screenshot (1975)

Screenshot (1976)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hello @Ajay-Dhangar 
can you please review this PR?

**Comment by SadafKausar2025** [comment]
hello Ajay
please review this PR and merge it

**Comment by SadafKausar2025** [comment]
Hello @Ajay-Dhangar 
Please merge this Pr .
So that I can work in another issue as well

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Pull request merged**
