### PR TITLE
Supply chain management DApp or Web 3 section

### LINKED ISSUE #3154: [Feature Request]: ADD Supply Chain Management DApp or Web 3 section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Blockchain Supply chain management plays a critical role in ensuring efficient operations and maintaining consumer trust. This project focuses on developing and deploying a decentralized application (DApp) powered by blockchain technology to streamline supply chain management processes.

### Use Case

Our DApp utilizes the inherent transparency and immutability of blockchain to provide a secure and transparent platform for tracking goods at every stage of the supply chain. Leveraging smart contracts, the DApp automates various tasks such as verifying product authenticity, recording transactions, and managing inventory in real-time.

### Benefits

_No response_

### Add ScreenShots

image

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by kartikmehta18**
## Related Issue

[Cite any related issue(s) this pull request addresses. If none, simply state "None”]
close #3154

## Description
Blockchain Supply chain management plays a critical role in ensuring efficient operations and maintaining consumer trust. This project focuses on developing and deploying a decentralized application (DApp) powered by blockchain technology to streamline supply chain management processes.

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

image

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have followed the code style guidelines of this project.
- [x] I have checked for any existing open issues that my pull request may address.
- [x] I have ensured that my changes do not break any existing functionality.
- [x] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [x] I have read the resources for guidance listed below.
- [x] I have followed security best practices in my code changes.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Please read the following resources before submitting your contribution:

- [ ] [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [ ] [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [ ] [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [ ] [Markdown Guide](https://www.markdownguide.org/)
- [ ] [MDX Documentation](https://mdxjs.com/docs/)
- [ ] [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- [ ] [Tabs: Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [ ] [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [ ] [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex) 

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **level1** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **level2**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Level1:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Level2:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Level3:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

### CODE REVIEW

**Review by Ajay-Dhangar — CHANGES_REQUESTED** [review]
@kartikmehta18, I've reviewed your project and I'm really impressed with the concept and the overall quality of the work. I think it's a great fit for our showcase, but there are a few bugs that need to be resolved before we can add it.

The main issue is that the CSS isn't working properly. This is causing some visual glitches and making the site difficult to use. I also found a few other minor bugs that should be easy to fix.

Once you've resolved these issues, please let me know and I'll be happy to review the project again and add it to our showcase.

Thank you for your work on this project. I look forward to seeing the finished product!

**Comment by Ajay-Dhangar** [comment]
@kartikmehta18, your project description is large so, you need follow
- **Site title:** <= 60 characters
- **Site description:** ≤120 characters

**Comment by kartikmehta18** [comment]
> @kartikmehta18, I've reviewed your project and I'm really impressed with the concept and the overall quality of the work. I think it's a great fit for our showcase, but there are a few bugs that need to be resolved before we can add it.
> 
> The main issue is that the CSS isn't working properly. This is causing some visual glitches and making the site difficult to use. I also found a few other minor bugs that should be easy to fix.
> 
> Once you've resolved these issues, please let me know and I'll be happy to review the project again and add it to our showcase.
> 
> Thank you for your work on this project. I look forward to seeing the finished product!

in this project I seen that but when u clone that repo n run project ,talwind  works properly , but when I deploy that project don't know automatically talwind got disturbed (if plz  you or anyone help me to solve this ) !!

**Comment by Ajay-Dhangar** [comment]
> > @kartikmehta18, I've reviewed your project and I'm really impressed with the concept and the overall quality of the work. I think it's a great fit for our showcase, but there are a few bugs that need to be resolved before we can add it.
> > The main issue is that the CSS isn't working properly. This is causing some visual glitches and making the site difficult to use. I also found a few other minor bugs that should be easy to fix.
> > Once you've resolved these issues, please let me know and I'll be happy to review the project again and add it to our showcase.
> > Thank you for your work on this project. I look forward to seeing the finished product!
> 
> in this project I seen that but when u clone that repo n run project ,talwind works properly , but when I deploy that project don't know automatically talwind got disturbed (if plz you or anyone help me to solve this ) !!

You need to read the docs of vercel for this issue. In most cases, you can find the answer to your question in the documentation. If you can't solve the problem after reading the docs, send me a message and I'll help you.

**Pull request merged**
