### PR TITLE
Added solution GFG-0102 Minimum BST Sum Subtree Solution

### LINKED ISSUE #1428: [Feature Request]: GFG-0102 Minimum BST Sum Subtree Solution
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Solution to the problem

### Use Case

Get the solution instantly

### Benefits

for better user enaggement

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Damini2004**
## Related Issue

Fix #1428

## Description

Solution added
## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have followed the code style guidelines of this project.
- [x] I have checked for any existing open issues that my pull request may address.
- [x] I have ensured that my changes do not break any existing functionality.
- [x] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [x] I have read the resources for guidance listed below.
- [x] I have followed security best practices in my code changes.

## Resources for Guidance

Please read the following resources before submitting your contribution:

- [ ] [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [ ] [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [ ] [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [ ] [Markdown Guide](https://www.markdownguide.org/)
- [ ] [MDX Documentation](https://mdxjs.com/docs/)
- [ ] [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- [ ] [Tabs: Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [ ] [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [ ] [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex) 

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **level1** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **level2**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Level1:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Level2:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Level3:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

### CODE REVIEW

**Comment by Damini2004** [comment]
@Ajay-Dhangar Any changes ??

**Comment by Ajay-Dhangar** [comment]
@Damini2004 , you need to sync your fork or clone of the repository because you have created 3 PRs, but all the files are included in each of these PRs. Since I have already merged them, you only need to create a PR for the 'Minimum BST Sum Subtree' now.

**Comment by Damini2004** [comment]
@Ajay-Dhangar Changes done 
Kindly review the PR again

**Review by Ajay-Dhangar — CHANGES_REQUESTED** [review]
update code based on suggestions

**Comment by Ajay-Dhangar** [comment]
@Damini2004 you need to follow basic commands to solved conflicts error

Step 1:  Clone our project in your `vs code` .

```bash
git clone https://github.com/Damini2004/codeharborhub.git
```

Step 2: From your project repository, check out a new branch and test the changes.

```
git checkout -b Damini2004-GFG-0102 main
git pull https://github.com/Damini2004/codeharborhub.git GFG-0102
```
Step 3: Merge the changes and update on GitHub.

```bash
git checkout main
git merge --no-ff Damini2004-GFG-0102
git push origin main
```


### And if you need any help then ask me I will help you

**Comment by Damini2004** [comment]
image
This error is arising 
May be i have to raise another PR.

**Comment by Ajay-Dhangar** [comment]
> image This error is arising May be i have to raise another PR.

### Checkout both file

```
dsa-solutions/gfg-solutions/Hard/0101-0200/0106-Travelling-Salesperson-Problem.md
dsa-solutions/gfg-solutions/Hard/0101-0200/0114-Water-Connection-Problem.md
```

**Comment by Damini2004** [comment]
image
Still it is their

**Pull request closed without merging**
