### PR TITLE
fix issue with PR #1461

### LINKED ISSUE #1409: [Feature Request]: LeetCode Q: 945
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding solution to the LeetCode Question 945.

### Use Case

Helpful for user visiting the website to find solutions

### Benefits

Helpful for user visiting the website to find solutions

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by vansh-codes**
## Related Issue
[Cite any related issue(s) this pull request addresses. If none, simply state "None”]

Closes #1409 
### I am creating this PR again as said by Sanjay Sir to get my PR updated on the leaderboard

This is the link to my old PR which is not updated: 
https://github.com/CodeHarborHub/codeharborhub.github.io/pull/1461

Corresponding issue with that PR: https://github.com/CodeHarborHub/codeharborhub.github.io/issues/1409

[Please include a brief description of the changes or features added]

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have followed the code style guidelines of this project.
- [x] I have checked for any existing open issues that my pull request may address.
- [x] I have ensured that my changes do not break any existing functionality.
- [x] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [x] I have read the resources for guidance listed below.
- [x] I have followed security best practices in my code changes.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Please read the following resources before submitting your contribution:

- [x] [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [x] [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [x] [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [x] [Markdown Guide](https://www.markdownguide.org/)
- [x] [MDX Documentation](https://mdxjs.com/docs/)
- [x] [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- [x] [Tabs: Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [x] [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [x] [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex) 

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **level1** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **level2**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Level1:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Level2:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Level3:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

### CODE REVIEW

**Comment by vansh-codes** [comment]
@Ajay-Dhangar Hi, the PR i mentioned is not updated on the leaderboard, thats why I am creating this PR again.
I have 3 more PR's like this, please let me know shall I create 3 more PR's addressing those individual PR's or is there any other way to do this? 
Also I need to update something in code to create a PR, in this I just wrote a comment in the file which was added by me, for next 3 pr's what shall I do??
Please let me know so I can raise 3 more PR's which are not updated on the leaderboard

**Comment by Ajay-Dhangar** [comment]
> 

@vansh-codes, I assigned you level3 for all your PRs (3-3 group), you need only edit something or maybe even just white space then create PRs and mention your previous PRs that are not counted on the leaderboard.

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Comment by vansh-codes** [comment]
> > 
> 
> @vansh-codes, I assigned you level3 for all your PRs (3-3 group), you need only edit something or maybe even just white space then create PRs and mention your previous PRs that are not counted on the leaderboard.

@Ajay-Dhangar Sorry I didnt understood what you mean, you mentioned level 3 but you added level 2
Can you please clear what you mean and now how many PR's more I have to create?

**Pull request merged**
