### PR TITLE
[Feature]: Add Output in React.Js Course in Docs section

### LINKED ISSUE #3922: [Feature]: Add `Output` in `React.Js ` Course in `Docs` section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

- In `/docs` section `React.Js ` course only available on the `code` doesn't show `output`.

### Actual Work 

Screenshot from 2024-07-26 21-18-58

Screenshot from 2024-07-26 21-19-13

Screenshot from 2024-07-26 21-19-04

### Expected Behaviour

[Screencast from 2024-07-24 09-08-03.webm](https://github.com/user-attachments/assets/9a3e202a-e512-45c1-b8a7-dfa13b1913c6)

[Screencast from 2024-07-24 09-08-58.webm](https://github.com/user-attachments/assets/b5a920bb-5621-444b-b3b9-badfbcbc12a2)

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sivaprasath2004**
## Related Issue

Fixes #3922 

## Description

[Feature]: Add Output in React.Js Course in Docs section

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

Screenshot from 2024-07-27 13-38-01

[Screencast from 2024-07-27 13-38-12.webm](https://github.com/user-attachments/assets/e93b05a4-295c-4ec9-8d0f-f1e8c3703e1c)

[Screencast from 2024-07-27 13-38-31.webm](https://github.com/user-attachments/assets/5832ea6a-7ff0-40e2-acf3-c3e1ae617ec3)

[Screencast from 2024-07-27 13-41-38.webm](https://github.com/user-attachments/assets/613643e9-173b-4d58-91de-eaf5c1e6df29)

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have followed the code style guidelines of this project.
- [ ] I have checked for any existing open issues that my pull request may address.
- [ ] I have ensured that my changes do not break any existing functionality.
- [ ] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [ ] I have read the resources for guidance listed below.
- [ ] I have followed security best practices in my code changes.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Please read the following resources before submitting your contribution:

- [x] [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [ ] [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [ ] [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [x] [Markdown Guide](https://www.markdownguide.org/)
- [ ] [MDX Documentation](https://mdxjs.com/docs/)
- [ ] [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- [x] [Tabs: Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [ ] [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [ ] [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex) 

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **level1** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **level2**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Level1:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Level2:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Level3:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

### CODE REVIEW

**Comment by sivaprasath2004** [comment]
Hello @Ajay-Dhangar please merge this..

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Review by Ajay-Dhangar — APPROVED** [review]
⌚ for ⚠️

**Comment by Ajay-Dhangar** [comment]
@sivaprasath2004, I think you'll need to debug your code and run the command `npm run build`. Can you try that and see if it helps?

**Comment by sivaprasath2004** [comment]
Hello @Ajay-Dhangar , I will try to `npm run build` but this is show this error

Screenshot from 2024-07-27 19-16-15


If this is not work..

**Comment by sivaprasath2004** [comment]
Screenshot from 2024-07-27 20-02-27


Hello @Ajay-Dhangar increase the limit it's can be work properly...

**Pull request closed without merging**
