### PR TITLE
Create Introduction-to-Internet-of-Things-(IoT).md

### LINKED ISSUE #4146: [Documentation Update]:  create a new file Introduction-to-Internet-of-Things-(IoT).md
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The Internet of Things (IoT) is revolutionizing the way we interact with the world around us. By connecting everyday objects to the internet, IoT enables smarter and more efficient systems. This guide will introduce you to the fundamentals of IoT, its architecture, key components, applications, and future trends.

### Suggested Change

Adding this file to the blog folder

### Rationale

_No response_

### Urgency

High

### Acknowledgements

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository
- [X] I have read and followed the Contribution Guidelines
- [X] I have followed the code style guidelines of this project
- [X] I have checked for any existing open issues that my pull request may address
- [X] I have ensured that my changes do not break any existing functionality
- [X] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently
- [X] I have read the resources for guidance listed below
- [X] I have not used AI-generated content (e.g., ChatGPT, other AI tools)
- [X] I have not used content from existing sites (e.g., text, images)
- [X] I have followed all security rules and only shared trusted resources

### PR DESCRIPTION
**Pull request by AKSHITHA-CHILUKA**
## Related Issue

Fix #4146 

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [x] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

[Attach any relevant screenshots or videos demonstrating the changes]

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have followed the code style guidelines of this project.
- [x] I have checked for any existing open issues that my pull request may address.
- [x] I have ensured that my changes do not break any existing functionality.
- [x] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [x] I have read the resources for guidance listed below.
- [x] I have followed security best practices in my code changes.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Please read the following resources before submitting your contribution:

- [x] [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [x] [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [x] [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [x] [Markdown Guide](https://www.markdownguide.org/)
- [x] [MDX Documentation](https://mdxjs.com/docs/)
- [x] [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- [x] [Tabs: Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [x] [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [x] [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex) 

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **level1** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **level2**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Level1:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Level2:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Level3:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

### CODE REVIEW

**Comment by AKSHITHA-CHILUKA** [comment]
please review and merge

**Review by Ajay-Dhangar — CHANGES_REQUESTED** [review]
Hi @AKSHITHA-CHILUKA, I’m taking a look at your PR. Your “Introduction to Internet of Things (IoT)” blog post is informative and looks great! I’m almost ready to merge it, but first I have a few suggestions. 

First, please define yourself as the author in the author file. Second, you need to follow our blog structure, which you can see in our previous files. Finally, please include some information about yourself in the author file.

Once you’ve made those changes, I’ll be happy to merge your PR.

**Review by AKSHITHA-CHILUKA — COMMENTED** [review]
followed the blog structure

**Comment by AKSHITHA-CHILUKA** [comment]
should i create a new pr

**Comment by Ajay-Dhangar** [comment]
@AKSHITHA-CHILUKA, I can help you with that. The content of the "Introduction to Internet of Things (IoT)" blog post is a good start, but to be suitable for publication, it will need to be more advanced. I suggest you read through some of our previous blog posts to get an idea of the kind of content we're looking for.

Once you have a good understanding of our blog structure, you can revise and expand your post. Be sure to define yourself as the author in the [author](https://github.com/CodeHarborHub/codeharborhub.github.io/blob/98ba5b8ff703d0cbcfdbbbd34983d54b7147181c/blog/authors.yml#L73) file and include some information about yourself.

If you have any further questions or need additional assistance, feel free to reach out.

**Comment by AKSHITHA-CHILUKA** [comment]
okay i will make the changes and request a new pr

**Pull request closed without merging**
