### PR TITLE
Added  authentication using firebase

### LINKED ISSUE #2887: [Feature Request]: Adding login / signup authentication.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding the login / signup authentication using firebase auth.

### Use Case

It will  help the  admin to  track the  performance of the website based on registered users.

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by happyrao78**
Added google login/logout authentication using firebase.
Fix #2887

### CODE REVIEW

**Review by Ajay-Dhangar — CHANGES_REQUESTED** [review]
@happyrao78, using `public/index.html` directly is not considered best practice. Instead, try to organize your code into components, either as function or class components. Create a directory for authentication routes in `/src/pages/auth/index.tsx` and follow best practices.

**Comment by Ajay-Dhangar** [comment]
@happyrao78, my suggestion for you is that you don't need to add backend or authentication, as we've already implemented them in another repository for our site. However, as a learning exercise, I've assigned this task to you. But I want to you can please raise a new issue. Your contributions are highly valued, and I encourage you to participate actively in GSSOC'24 open source to build your profile. After GSSOC, we can discuss how you can further engage with us on this project.

**Comment by happyrao78** [comment]
> @happyrao78, using `public/index.html` directly is not considered best practice. Instead, try to organize your code into components, either as function or class components. Create a directory for authentication routes in `/src/pages/auth/index.tsx` and follow best practices.

So, Do I need to fix this for getting the PR Merged ?

**Comment by Ajay-Dhangar** [comment]
> > @happyrao78, using `public/index.html` directly is not considered best practice. Instead, try to organize your code into components, either as function or class components. Create a directory for authentication routes in `/src/pages/auth/index.tsx` and follow best practices.
> 
> So, Do I need to fix this for getting the PR Merged ?

However, as a best practice, we maintain our backend in a separate repository. This approach isn't suitable for our current needs, but it could be valuable for beginners. Writing a blog post on this topic would be helpful.

**Comment by Ajay-Dhangar** [comment]
@happyrao78, I suggest closing this pull request and instead create a new one specifically for a blog post.

**Pull request closed without merging**
