### PR TITLE
Dbms basics docs added

### PR DESCRIPTION
**Pull request by Vipullakum007**
## Related Issue

Fixed : #638 

## Description

1. i have added new Tutorial on "DBMS"

and added this files

Screenshot 2024-06-07 135246
 
2. added image according to topic

image

3. added tables to more readable for user 

image

4. table with diagram
Screenshot (709)

5. added another note like stuff also
Screenshot 2024-06-07 132512

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

https://github.com/CodeHarborHub/codeharborhub.github.io/assets/127659443/78ee4df7-75ff-4ba3-a02c-7a047fd85d54

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context

[Include any additional information or context that might be helpful for reviewers.]

## Resources for Guidance

Here are some resources that may be helpful as you contribute to CodeHarborHub:
- [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [Markdown Guide](https://www.markdownguide.org/)
- [MDX Documentation](https://mdxjs.com/docs/)
- [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- Tabs: [Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex)

### CODE REVIEW

**Comment by Vipullakum007** [comment]
hey @Ajay-Dhangar , i have **table** , **note** ,**diagram**  and **table with diagram** like stuff to make it professional as you suggest.
after review it if you want please make it level 3

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Comment by Ajay-Dhangar** [comment]
@Vipullakum007 Great but If you want to use mermaid diagram then you can also, used for best practice because our site in fully supported to mermaid diagram and check out https://mermaid.js.org/ or try some code https://mermaid.js.org/syntax/entityRelationshipDiagram.html for ER - Diagram and more....

**Comment by Ajay-Dhangar** [comment]
> @Vipullakum007 Great but If you want to use mermaid diagram then you can also, used for best practice because our site in fully supported to mermaid diagram and check out https://mermaid.js.org/ or try some code https://mermaid.js.org/syntax/entityRelationshipDiagram.html for ER - Diagram and more....

@Vipullakum007, would you be interested in working on this? Using images can slow down our site's performance. Instead, we can use Mermaid to generate diagrams with code. This approach will help make our site faster and more optimized.

**Comment by Ajay-Dhangar** [comment]
> > @Vipullakum007 Great but If you want to use mermaid diagram then you can also, used for best practice because our site in fully supported to mermaid diagram and check out https://mermaid.js.org/ or try some code https://mermaid.js.org/syntax/entityRelationshipDiagram.html for ER - Diagram and more....
> 
> @Vipullakum007, would you be interested in working on this? Using images can slow down our site's performance. Instead, we can use Mermaid to generate diagrams with code. This approach will help make our site faster and more optimized.

If you want to level3 then work on it.

**Comment by Vipullakum007** [comment]
> > > @Vipullakum007 Great but If you want to use mermaid diagram then you can also, used for best practice because our site in fully supported to mermaid diagram and check out https://mermaid.js.org/ or try some code https://mermaid.js.org/syntax/entityRelationshipDiagram.html for ER - Diagram and more....
> > 
> > 
> > @Vipullakum007, would you be interested in working on this? Using images can slow down our site's performance. Instead, we can use Mermaid to generate diagrams with code. This approach will help make our site faster and more optimized.
> 
> If you want to level3 then work on it.

hey @Ajay-Dhangar  , i have added mermaid diagram you can review it thx for your information i don't have idea about this tool this very helpful @Ajay-Dhangar Thank you again. you can make it level 3

**Review by Ajay-Dhangar — APPROVED** [review]
done

**Comment by Vipullakum007** [comment]
> done
hey @Ajay-Dhangar , done but you forgot to make it **level 3.**

**Pull request merged**
