### PR TITLE
Docs: Added Solutions to Leetcode 916

### LINKED ISSUE #1973: [Feature Request]:Leetcode Problem 916 - ( Word Subsets - Medium)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Provide Solution To Leetcode Problem  916 - ( Word Subsets )

### Use Case

I would add proper solutions for the problem in three different programing languages i.e C++,Java,and Python with proper documentation

### Benefits

Users can access solution to problem 916

### Add ScreenShots

N/A

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by shreyash3087**
## Related Issue

Closes #1973

## Description

This PR adds the solutions to leetcode problem 916 - ( Word Subsets )

## Type of PR

- [ ] Bug fix
- [ ] Feature enhancement
- [X] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

screencapture-localhost-3000-dsa-solutions-lc-solutions-0900-0999-word-subsets-2024-06-25-00_23_10

## Checklist
- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines.
- [X] I have tested the changes thoroughly before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have followed the code style guidelines of this project.
- [X] I have checked for any existing open issues that my pull request may address.
- [X] I have ensured that my changes do not break any existing functionality.
- [X] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [X] I have read the resources for guidance listed below.
- [X] I have followed security best practices in my code changes.

## Additional Context

N/A

### CODE REVIEW

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Comment by sanjay-kv** [comment]
image
@shreyash3087 This repo has limitation of 150 points if you are contributing documentation

**Comment by shreyash3087** [comment]
@sanjay-kv Alright sir,i wasnt aware about the limitations on the Repo for docs,sorry about that !

**Comment by shreyash3087** [comment]
@Ajay-Dhangar how do we check the limitation on the repo?

**Comment by sanjay-kv** [comment]
https://github.com/GSSoC24/Contributor/tree/main/gssoc-guidelines

This has mentioned on the guidelines. Any technical issue you contribute to the repo doesn't come under this limitation to this repo. Only documentation. 

We have mailed Everyone, Github discussion update, Linkedin Post update, Discord announcement has been made regarding the same 

For admin we will give more beginner users who can work on the documentation. there is new batch training program from next week.

**Pull request merged**
