### PR TITLE
[Feature]: Add Angular Course

### LINKED ISSUE #3451: [Feature]: Add `Angular` Course
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hello @Ajay-Dhangar ,

- If I want to add the `Angular` course .
- please assign me.

### Use Case

[Screencast from 2024-07-16 22-53-38.webm](https://github.com/user-attachments/assets/09ad8168-53b1-421a-bacb-955062cc9f07)

### Benefits

_No response_

### Add ScreenShots

_No response_

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by sivaprasath2004**
## Related Issue

Fixes #3451 

## Description

[Feature]: Add Angular Course

## Type of PR

- [ ] Bug fix
- [x] Feature enhancement
- [ ] Documentation update
- [ ] Security enhancement
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)

[Screencast from 2024-07-17 17-46-59.webm](https://github.com/user-attachments/assets/fd4307ae-fa97-4dcf-82b1-c9bc4c69895a)

## Checklist
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines.
- [x] I have tested the changes thoroughly before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have followed the code style guidelines of this project.
- [x] I have checked for any existing open issues that my pull request may address.
- [x] I have ensured that my changes do not break any existing functionality.
- [x] Each contributor is allowed to create a maximum of 4 issues per day. This helps us manage and address issues efficiently.
- [ ] I have read the resources for guidance listed below.
- [ ] I have followed security best practices in my code changes.
 

## Resources for Guidance

Please read the following resources before submitting your contribution:

- [x] [Code Harbor Hub Community Features](https://www.codeharborhub.live/community/features)
- [ ] [Docusaurus Documentation](https://docusaurus.io/docs/create-doc)
- [ ] [React.js Documentation](https://legacy.reactjs.org/docs/getting-started.html)
- [x] [Markdown Guide](https://www.markdownguide.org/)
- [ ] [MDX Documentation](https://mdxjs.com/docs/)
- [ ] [Mermaid Documentation](https://mermaid.js.org/)

**Resources for DSA Features on Our Site:**

- [x] [Tabs: Switch Languages](https://www.codeharborhub.live/community/features#multi-language-support-code-blocks)
- [ ] [Line Numbering](https://www.codeharborhub.live/community/features#line-numbering)
- [ ] [Math Equations](https://www.codeharborhub.live/community/features#math-equations-with-katex) 

## Contribution Guidelines

Thank you for considering contributing to our project! To ensure smooth collaboration and effective contribution management, please adhere to the following guidelines:

### Issue Creation

1. **Limit on Issues:**
   - Each contributor is allowed to create a maximum of **4 issues per day**. This helps us manage and address issues efficiently.

### Contribution Levels

2. **Basic Contributions:**
   - This project is primarily focused on documentation. Most of the setup has been completed, so contributors will generally need to work on basic code tasks, such as writing tests.
   - For these tasks, issues will be assigned the **level1** label.

3. **Acknowledging Hard Work:**
   - If a contributor puts in significant effort on a task, the issue will be upgraded to **level2**. This is our way of recognizing and appreciating extra effort.

4. **Feature Additions and Component Work:**
   - Contributors working on new features or components using JSX/TSX will be assigned a level based on the complexity and quality of their work.
   - The more complex and valuable the contribution, the higher the level assigned.

### Level Definitions

- **Level1:**
  - Tasks are straightforward, such as fixing minor bugs, writing tests, or making simple documentation updates.
- **Level2:**
  - Tasks require more effort, such as addressing complex bugs, improving existing features, or making substantial documentation improvements.
- **Level3:**
  - Tasks are highly complex and involve significant new feature development, major refactoring, or extensive contributions to the project’s core components.

We look forward to your contributions and appreciate your effort in helping us improve the project!

### CODE REVIEW

**Comment by sivaprasath2004** [comment]
@Ajay-Dhangar kindly give as `level3` , because I will work my best to ensure the highest quality in my work.

**Review by shivay-coding — APPROVED** [review]
This pull request includes a new Angular course, which is a great addition to CodeHarborHub. I think Angular is a really useful skill for developers to have, so I'm glad we're providing this resource. 

The course covers a lot of important Angular topics, including routing, components, forms, and HTTP. The lessons are clear and concise, and they include plenty of code examples. I'm confident that this course will help developers learn Angular quickly and effectively.

I did notice a few minor typos and grammatical errors throughout the course materials. I've made a note of them and I'm happy to provide more feedback if needed.

Overall, I think this is a valuable addition to CodeHarborHub. I approve this pull request and I look forward to seeing more high-quality content like this in the future.

**Comment by sivaprasath2004** [comment]
@shivay-coding could you please add `level3` because I will this particular `course` I search to many topics & sites  to cover. Kindly give `level3`

**Review by Ajay-Dhangar — APPROVED** [review]
Done

**Comment by sivaprasath2004** [comment]
@Ajay-Dhangar could you please merge this ..

**Comment by Ajay-Dhangar** [comment]
> @shivay-coding could you please add `level3` because I will this particular `course` I search to many topics & sites to cover. Kindly give `level3`

@sivaprasath2004, I appreciate your work, but your content looks okay. However, it doesn't fully align with all our features to make it more interactive and better. I have already shared all the necessary guidance and features with you, and it should be easy for you to follow. I'm awaiting your response; if you're open to updating it, you can give it a try. I'll give you good level, and based on your response, I may proceed with the merge.

**Comment by Ajay-Dhangar** [comment]
> @shivay-coding could you please add `level3` because I will this particular `course` I search to many topics & sites to cover. Kindly give `level3`

@sivaprasath2004, I appreciate your work, but your content looks okay. However, it doesn't fully align with all our features to make it more interactive and better. I have already shared all the necessary guidance and features with you, and it should be easy for you to follow. I'm awaiting your response; if you're open to updating it, you can give it a try. I'll give you a good level, and based on your response, I may proceed with the merge.

**Comment by sivaprasath2004** [comment]
@Ajay-Dhangar  yes proceed

**Comment by Ajay-Dhangar** [comment]
> @shivay-coding could you please add `level3` because I will this particular `course` I search to many topics & sites to cover. Kindly give `level3`

@sivaprasath2004, I appreciate your work, but your content looks okay. However, it doesn't fully align with all our features to make it more interactive and better. I have already shared all the necessary guidance and features with you, and it should be easy for you to follow. I'm awaiting your response; if you're open to updating it, you can give it a try. I'll give you a good level, and based on your response, I may proceed with the merge.

**Pull request merged**
